[package]
name = "o66"
version = "0.1.0"
authors = ["Yusuke Endoh <mame@ruby-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = "2.33"
rand = "0.8"
rayon = "1.5"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
js-sys = "0.3"